//! Handler generation for the page! macro.
//!
//! Generates handler ID assignments for widget events.
//! The actual handler dispatch is done by the runtime using the
//! dispatch methods generated by #[app_impl] / #[modal_impl].
//!
//! Handler arguments are serialized into element data fields:
//! - `on_click` = "handler_name"
//! - `on_click_arg_0` = arg0.to_string()
//! - `on_click_arg_1` = arg1.to_string()
//! etc.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::macros::page::ast::{HandlerArg, HandlerAttr};

/// Generate handler ID method calls for a widget.
///
/// Each handler becomes method calls like:
/// ```ignore
/// .on_click_id(rafter::HandlerId::new("handler_name"))
/// .data("on_click_arg_0", arg0.to_string())
/// .data("on_click_arg_1", arg1.to_string())
/// ```
///
/// The runtime will call `dispatch(handler_id, args, ...)` when the event fires,
/// which routes to the correct handler method with proper context and arguments.
pub fn generate_handler_calls(handlers: &[HandlerAttr]) -> Vec<TokenStream> {
    handlers.iter().flat_map(generate_single_handler).collect()
}

/// Generate handler ID and argument data calls
fn generate_single_handler(handler: &HandlerAttr) -> Vec<TokenStream> {
    let event_method = &handler.event; // on_click, on_change, etc.
    let handler_name = &handler.handler;
    let handler_name_str = handler_name.to_string();
    let event_str = event_method.to_string();

    // Convert event method to ID method: on_click -> on_click_id
    let id_method = format_ident!("{}_id", event_method);

    let mut calls = vec![quote! {
        .#id_method(rafter::HandlerId::new(#handler_name_str))
    }];

    // Add data calls for each argument
    for (i, arg) in handler.args.iter().enumerate() {
        let key = format!("{}_arg_{}", event_str, i);

        match arg {
            HandlerArg::Expr(expr) => {
                // Serialize expression value to string
                calls.push(quote! {
                    .data(#key, (#expr).to_string())
                });
            }
            HandlerArg::Context(_) => {
                // Context args are handled by dispatch, not stored in data
                // Skip them in the arg index count
            }
        }
    }

    calls
}
