//! Context menu infrastructure for rafter.
//!
//! Context menus are right-click menus with options and submenus. They integrate
//! into the runtime similar to modals but with different lifecycle:
//! - Only one active at a time (no stacking)
//! - Instant dismiss on click outside or option selection
//! - Hover-based submenu expansion using focus/blur events
//!
//! # Example
//!
//! ```ignore
//! #[context_menu]
//! fn record_menu(&self, record_id: String) {
//!     option("Delete", delete(record_id.clone()));
//!     option("Edit", edit(record_id.clone()));
//!     
//!     separator();
//!     
//!     submenu("Export") {
//!         option("CSV", export_csv(record_id.clone()));
//!         option("JSON", export_json(record_id.clone()));
//!     }
//! }
//!
//! // In a handler:
//! cx.context_menu(self.record_menu(row.id), x, y).await;
//! ```

use crate::handler_context::Handler;
use std::sync::Arc;

// =============================================================================
// Menu Option Types
// =============================================================================

/// A single option in a context menu.
#[derive(Clone)]
pub enum MenuOption {
    /// Clickable menu item with optional submenu.
    Item {
        /// Display label for the option.
        label: String,
        /// Handler to invoke when clicked (not called for items with submenus).
        handler: Option<Handler>,
        /// Whether this option is disabled (shown but not clickable).
        disabled: bool,
        /// Child submenu (if any).
        submenu: Option<Box<ContextMenuDefinition>>,
    },
    /// Visual separator line.
    Separator,
}

impl MenuOption {
    /// Create a clickable item without a submenu.
    pub fn item(label: impl Into<String>, handler: Handler) -> Self {
        Self::Item {
            label: label.into(),
            handler: Some(handler),
            disabled: false,
            submenu: None,
        }
    }

    /// Create a disabled item.
    pub fn disabled_item(label: impl Into<String>) -> Self {
        Self::Item {
            label: label.into(),
            handler: None,
            disabled: true,
            submenu: None,
        }
    }

    /// Create an item with a submenu.
    pub fn submenu_item(label: impl Into<String>, submenu: ContextMenuDefinition) -> Self {
        Self::Item {
            label: label.into(),
            handler: None,
            disabled: false,
            submenu: Some(Box::new(submenu)),
        }
    }

    /// Create a separator.
    pub fn separator() -> Self {
        Self::Separator
    }

    /// Check if this option has a submenu.
    pub fn has_submenu(&self) -> bool {
        matches!(
            self,
            MenuOption::Item {
                submenu: Some(_),
                ..
            }
        )
    }

    /// Get the submenu if this option has one.
    pub fn submenu(&self) -> Option<&ContextMenuDefinition> {
        match self {
            MenuOption::Item {
                submenu: Some(sm), ..
            } => Some(sm),
            _ => None,
        }
    }

    /// Get the handler if this option has one.
    pub fn handler(&self) -> Option<&Handler> {
        match self {
            MenuOption::Item {
                handler: Some(h), ..
            } => Some(h),
            _ => None,
        }
    }

    /// Check if this option is disabled.
    pub fn is_disabled(&self) -> bool {
        matches!(self, MenuOption::Item { disabled: true, .. })
    }

    /// Get the label for this option (None for separators).
    pub fn label(&self) -> Option<&str> {
        match self {
            MenuOption::Item { label, .. } => Some(label),
            MenuOption::Separator => None,
        }
    }
}

// =============================================================================
// Menu Definition
// =============================================================================

/// Complete definition of a context menu.
///
/// This is generated by the `#[context_menu]` macro and contains all options
/// with their handlers already captured.
#[derive(Clone)]
pub struct ContextMenuDefinition {
    /// All options in the menu.
    pub options: Vec<MenuOption>,
}

impl ContextMenuDefinition {
    /// Create a new empty menu definition.
    pub fn new() -> Self {
        Self {
            options: Vec::new(),
        }
    }

    /// Add an option to the menu.
    pub fn add_option(&mut self, option: MenuOption) {
        self.options.push(option);
    }

    /// Get an option by index.
    pub fn get_option(&self, index: usize) -> Option<&MenuOption> {
        self.options.get(index)
    }

    /// Get the handler for an option by index.
    pub fn get_handler(&self, index: usize) -> Option<&Handler> {
        self.get_option(index)?.handler()
    }

    /// Check if an option has a submenu.
    pub fn has_submenu(&self, index: usize) -> bool {
        self.get_option(index)
            .map(|o| o.has_submenu())
            .unwrap_or(false)
    }

    /// Get the submenu for an option by index.
    pub fn get_submenu(&self, index: usize) -> Option<&ContextMenuDefinition> {
        self.get_option(index)?.submenu()
    }

    /// Count of options in this menu.
    pub fn len(&self) -> usize {
        self.options.len()
    }

    /// Calculate the display width needed for this menu based on its content.
    pub fn calculate_width(&self) -> u16 {
        let mut max_width = 0u16;

        for option in &self.options {
            match option {
                MenuOption::Item { label, submenu, .. } => {
                    // Base width is label length
                    let mut width = label.len() as u16;

                    // Add gap (1) plus submenu indicator "→" (1) if present
                    if submenu.is_some() {
                        width += 2;
                    }

                    max_width = max_width.max(width);
                }
                MenuOption::Separator => {
                    // Separators don't affect width calculation
                }
            }
        }

        max_width
    }

    /// Check if the menu is empty.
    pub fn is_empty(&self) -> bool {
        self.options.is_empty()
    }
}

impl Default for ContextMenuDefinition {
    fn default() -> Self {
        Self::new()
    }
}

// =============================================================================
// Request & State
// =============================================================================

/// Request to show a context menu.
///
/// Created when a handler calls `cx.context_menu()` or `gx.context_menu()`.
/// The runtime picks this up and converts it to `ContextMenuState`.
pub struct ContextMenuRequest {
    /// The menu definition with all handlers.
    pub definition: ContextMenuDefinition,
    /// Requested screen position (x, y).
    pub position: (u16, u16),
}

impl ContextMenuRequest {
    /// Create a new context menu request.
    pub fn new(definition: ContextMenuDefinition, position: (u16, u16)) -> Self {
        Self {
            definition,
            position,
        }
    }
}

/// Active context menu state tracked by the runtime.
///
/// This is created from a `ContextMenuRequest` and tracks the menu's position
/// and any open submenus.
pub struct ContextMenuState {
    /// The menu definition.
    pub definition: ContextMenuDefinition,
    /// Requested position (before bounds checking).
    pub position: (u16, u16),
    /// Open submenu states (index of parent option + submenu state).
    pub open_submenus: Vec<OpenSubmenu>,
}

/// An open submenu within a context menu.
pub struct OpenSubmenu {
    /// Index of the parent option that opened this submenu.
    pub parent_index: usize,
    /// The submenu definition.
    pub definition: ContextMenuDefinition,
    /// Position of this submenu.
    pub position: (u16, u16),
    /// Recursively nested open submenus.
    pub open_submenus: Vec<OpenSubmenu>,
}

impl ContextMenuState {
    /// Create a new context menu state from a request.
    pub fn from_request(request: ContextMenuRequest) -> Self {
        Self {
            definition: request.definition,
            position: request.position,
            open_submenus: Vec::new(),
        }
    }

    /// Open a submenu for the given option index.
    pub fn open_submenu(&mut self, option_index: usize, position: (u16, u16)) {
        // Close any existing submenus first (only one submenu level open at a time)
        self.open_submenus.clear();

        if let Some(submenu_def) = self.definition.get_submenu(option_index) {
            self.open_submenus.push(OpenSubmenu {
                parent_index: option_index,
                definition: submenu_def.clone(),
                position,
                open_submenus: Vec::new(),
            });
        }
    }

    /// Close all submenus.
    pub fn close_submenus(&mut self) {
        self.open_submenus.clear();
    }

    /// Check if a submenu is open for the given option index.
    pub fn is_submenu_open(&self, option_index: usize) -> bool {
        self.open_submenus
            .iter()
            .any(|sm| sm.parent_index == option_index)
    }
}

// =============================================================================
// Builder API (for manual construction)
// =============================================================================

/// Builder for constructing context menus programmatically.
///
/// The `#[context_menu]` macro generates code that uses this internally.
pub struct ContextMenuBuilder {
    definition: ContextMenuDefinition,
}

impl ContextMenuBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self {
            definition: ContextMenuDefinition::new(),
        }
    }

    /// Add a clickable option.
    pub fn option(mut self, label: impl Into<String>, handler: Handler) -> Self {
        self.definition.add_option(MenuOption::item(label, handler));
        self
    }

    /// Add a disabled option.
    pub fn disabled_option(mut self, label: impl Into<String>) -> Self {
        self.definition.add_option(MenuOption::disabled_item(label));
        self
    }

    /// Add a separator.
    pub fn separator(mut self) -> Self {
        self.definition.add_option(MenuOption::separator());
        self
    }

    /// Add an option with a submenu.
    pub fn submenu(
        mut self,
        label: impl Into<String>,
        submenu: impl FnOnce(ContextMenuBuilder) -> ContextMenuBuilder,
    ) -> Self {
        let submenu_builder = submenu(ContextMenuBuilder::new());
        self.definition
            .add_option(MenuOption::submenu_item(label, submenu_builder.build()));
        self
    }

    /// Build the final menu definition.
    pub fn build(self) -> ContextMenuDefinition {
        self.definition
    }
}

impl Default for ContextMenuBuilder {
    fn default() -> Self {
        Self::new()
    }
}
